version: '3.8'

services:
  db:
    image: mysql:5.7.31
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.dev.db.env

  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql_data:
